# Generated by Django 4.2.7 on 2023-12-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(verbose_name='Tag ID')),
                ('eid', models.IntegerField(verbose_name='Entry ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='User ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('uname', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=2000, verbose_name='Password')),
                ('url', models.CharField(max_length=2500, verbose_name='URL')),
                ('expire', models.DateField(verbose_name='Expiration Date')),
                ('notes', models.CharField(max_length=2000, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='Tag Name')),
            ],
        ),
    ]
