# Generated by Django 4.2.7 on 2024-01-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='password',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='URL'),
        ),
    ]
